# syntax=docker/dockerfile:1.7

########################################
# 1) Dependencies
########################################
FROM node:20-alpine AS deps
WORKDIR /app
# Next on Alpine benefits from this
RUN apk add --no-cache libc6-compat
COPY package*.json ./
RUN npm ci --no-audit --prefer-offline

########################################
# 2) Build
########################################
FROM node:20-alpine AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Uses "next build" from your package.json scripts
RUN npm run build

########################################
# 3) Runtime (standalone)
########################################
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
# Copy the minimal standalone server and static assets
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
# server.js is generated by `output: 'standalone'`
CMD ["node", "server.js"]
